# Generated by Django 4.1.4 on 2022-12-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Mailing list start time.')),
                ('end_date', models.DateTimeField(verbose_name='Mailing list end time.')),
                ('content', models.TextField(verbose_name='Message text for client.')),
                ('sample', models.CharField(choices=[('tag', 'tag'), ('mobile operator code', 'mobile operator code')], max_length=150, verbose_name='Client properties filter')),
            ],
        ),
    ]
