# Generated by Django 4.1.4 on 2022-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_client_code_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sending_status',
            field=models.CharField(choices=[(1, 'Sent'), (2, 'No sent')], default=1, max_length=50, verbose_name='Sending status.'),
            preserve_default=False,
        ),
    ]
